  fields['bought_reason_cheaper'] = value('reason_for_bought_food_option').contains('Cheaper');
  fields['bought_reason_convenient'] = value('reason_for_bought_food_option').contains('Convenient');
  fields['bought_reason_healthy'] = value('reason_for_bought_food_option').contains('Healthy');
  fields['bought_reason_others_checked'] = value('reason_for_bought_food_option').contains('Others');
  fields['bought_reason_variety'] = value('reason_for_bought_food_option').contains('Variety of choices');
  fields['breeding_sites_no'] = value('has_breeding_sites_observed') == 'No';
  fields['breeding_sites_yes'] = value('has_breeding_sites_observed') == 'Yes';
  fields['canned_food_every_other_day'] = value('canned_preserved_food_frequency') == 'Every other day';
  fields['canned_food_every_week'] = value('canned_preserved_food_frequency') == 'Every week';
  fields['canned_food_everyday'] = value('canned_preserved_food_frequency') == 'Everyday';
  fields['canned_food_never'] = value('canned_preserved_food_frequency') == 'Never';
  fields['canned_food_sometimes'] = value('canned_preserved_food_frequency') == 'Sometimes';
  fields['carbonated_every_other_day'] = value('carbonated_beverage_frequency') == 'Every other day';
  fields['carbonated_every_week'] = value('carbonated_beverage_frequency') == 'Every week';
  fields['carbonated_everyday'] = value('carbonated_beverage_frequency') == 'Everyday';
  fields['carbonated_never'] = value('carbonated_beverage_frequency') == 'Never';
  fields['carbonated_occasionally'] = value('carbonated_beverage_frequency') == 'Occasionally';
  fields['carbonated_sometimes'] = value('carbonated_beverage_frequency') == 'Sometimes';
  fields['communication_internet'] = value('mode_of_communication').contains('Internet');
  fields['communication_others_checked'] = value('mode_of_communication').contains('Others');
  fields['communication_telephone'] = value('mode_of_communication').contains('Telephone');
  fields['communication_two_way_radio'] = value('mode_of_communication').contains('Two-way radio');
  fields['community_services_health'] = value('services_in_community').contains('Health Services');
  fields['community_services_livelihood'] = value('services_in_community').contains('Livelihood Services');
  fields['community_services_religious'] = value('services_in_community').contains('Religious services');
  fields['cooking_electric_stove'] = value('cooking_facility') == 'Electric stove';
  fields['cooking_firewood_charcoal'] = value('cooking_facility') == 'Firewood/charcoal';
  fields['cooking_gas_stove'] = value('cooking_facility') == 'Gas stove';
  fields['cooking_others_checked'] = value('cooking_facility') == 'Others';
  fields['dental_checkup_more_than_year'] = value('dental_checkup_frequency') == 'More than a year';
  fields['dental_checkup_once_year'] = value('dental_checkup_frequency') == 'Once a year';
  fields['dental_checkup_twice_year'] = value('dental_checkup_frequency') == 'Twice a year';
  fields['drainage_blind'] = value('drainage_system') == 'Blind drainage';
  fields['drainage_none'] = value('drainage_system') == 'None';
  fields['drainage_open'] = value('drainage_system') == 'Open drainage';
  fields['expenditure_10001_15000'] = value('monthly_family_expenditures') == '10,001-15,000';
  fields['expenditure_15001_20000'] = value('monthly_family_expenditures') == '15,001-20,000';
  fields['expenditure_20001_25000'] = value('monthly_family_expenditures') == '20,001-25,000';
  fields['expenditure_25001_30000'] = value('monthly_family_expenditures') == '25,001-30,000';
  fields['expenditure_30001_35000'] = value('monthly_family_expenditures') == '30,001-35,000';
  fields['expenditure_35001_40000'] = value('monthly_family_expenditures') == '35,001-40,000';
  fields['expenditure_40001_45000'] = value('monthly_family_expenditures') == '40,001-45,000';
  fields['expenditure_45001_50000'] = value('monthly_family_expenditures') == '45,001-50,000';
  fields['expenditure_50001_above'] = value('monthly_family_expenditures') == '50,001 and above';
  fields['expenditure_5001_10000'] = value('monthly_family_expenditures') == '5,001-10,000';
  fields['expenditure_less_5000'] = value('monthly_family_expenditures') == 'Less than 5,000';
  fields['financial_source_business'] = value('financial_sources').contains('Business');
  fields['financial_source_employment'] = value('financial_sources').contains('Employment');
  fields['financial_source_others_checked'] = value('financial_sources').contains('Others');
  fields['financial_source_others'] = value('financial_sources_other');
  fields['financial_source_pension'] = value('financial_sources').contains('Pension');
  fields['food_bought_outside'] = value('food_prepared_for_mealtime') == 'Bought outside';
  fields['food_prepared_home'] = value('food_prepared_for_mealtime') == 'Prepared at home';
  fields['food_storage_covered'] = value('food_storage_cover_status') == 'Covered';
  fields['food_storage_uncovered'] = value('food_storage_cover_status') == 'Uncovered';
  fields['garbage_storage_container'] = value('garbage_storage') == 'Container';
  fields['garbage_storage_none'] = value('garbage_storage') == 'None';
  fields['grilled_food_every_other_day'] = value('grilled_food_frequency') == 'Every other day';
  fields['grilled_food_every_week'] = value('grilled_food_frequency') == 'Every week';
  fields['grilled_food_everyday'] = value('grilled_food_frequency') == 'Everyday';
  fields['grilled_food_never'] = value('grilled_food_frequency') == 'Never';
  fields['grilled_food_sometimes'] = value('grilled_food_frequency') == 'Sometimes';
  fields['health_budget_amount'] = value('health_budget_amount_per_year_php');
  fields['health_budget_available'] = value('health_budget_expenditures_availability') == 'Available';
  fields['health_budget_not_available'] = value('health_budget_expenditures_availability') == 'Not Available';
  fields['health_restored_by_faith_healers'] = value('cultural_belief_health_restoration').contains('Health can be restored by faith healers');
  fields['health_restored_by_god_faith'] = value('cultural_belief_health_restoration').contains('Health can be restored by God/other spiritual faith');
  fields['health_restored_by_health_personnel'] = value('cultural_belief_health_restoration').contains('Health can be restored by health personnel, e.g. doctors, nurses');
  fields['health_restored_by_supernatural_power'] = value('cultural_belief_health_restoration').contains('Health can be restored by supernatural power, e.g. tawas, hilot, hula');
  fields['home_lease_to_own'] = value('home_ownership') == 'Lease/Least to own';
  fields['home_owned'] = value('home_ownership') == 'Owned';
  fields['home_professional_squatters'] = value('home_ownership') == 'Professional squatters';
  fields['home_rent_free'] = value('home_ownership') == 'Rent-free';
  fields['home_rented'] = value('home_ownership') == 'Rented';
  fields['home_squatting_informal_settlers'] = value('home_ownership') == 'Squatting/informal settlers';
  fields['housing_congestion_no'] = value('housing_congestion_observed') == 'No';
  fields['housing_congestion_yes'] = value('housing_congestion_observed') == 'Yes';
  fields['illness_cause_other_person'] = value('cultural_orientation_illness').contains('Illness is caused by other person');
  fields['illness_cause_others_checked'] = value('cultural_orientation_illness').contains('Others');
  fields['illness_cause_others'] = value('cultural_orientation_illness_other');
  fields['illness_cause_physiologic'] = value('cultural_orientation_illness').contains('Illness is caused by physiologic factor, e.g. infection');
  fields['illness_cause_punishment_from_god'] = value('cultural_orientation_illness').contains('Illness is a punishment from God');
  fields['illness_cause_supernatural'] = value('cultural_orientation_illness').contains('Illness is caused by supernatural phenomenon, e.g. kulam, balis');
  fields['illness_cause_weather_change'] = value('cultural_orientation_illness').contains('Illness is caused by change in weather');
  fields['income_10001_15000'] = value('monthly_family_income_combined') == '10,001-15,000';
  fields['income_15001_20000'] = value('monthly_family_income_combined') == '15,001-20,000';
  fields['income_20001_25000'] = value('monthly_family_income_combined') == '20,001-25,000';
  fields['income_25001_30000'] = value('monthly_family_income_combined') == '25,001-30,000';
  fields['income_30001_35000'] = value('monthly_family_income_combined') == '30,001-35,000';
  fields['income_35001_40000'] = value('monthly_family_income_combined') == '35,001-40,000';
  fields['income_40001_45000'] = value('monthly_family_income_combined') == '40,001-45,000';
  fields['income_45001_50000'] = value('monthly_family_income_combined') == '45,001-50,000';
  fields['income_50001_above'] = value('monthly_family_income_combined') == '50,001 and above';
  fields['income_5001_10000'] = value('monthly_family_income_combined') == '5,001-10,000';
  fields['income_adequate'] = value('family_income_adequacy') == 'Adequate';
  fields['income_less_5000'] = value('monthly_family_income_combined') == 'Less than 5,000';
  fields['income_not_adequate'] = value('family_income_adequacy') == 'Not Adequate';
  fields['industrial_establishment_no'] = value('has_industrial_establishment_or_factory_observed') == 'No';
  fields['industrial_establishment_yes'] = value('has_industrial_establishment_or_factory_observed') == 'Yes';
  fields['institution_brgy_hall'] = value('institutional_facilities').contains('Brgy. Hall');
  fields['institution_church'] = value('institutional_facilities').contains('Church');
  fields['institution_health_station'] = value('institutional_facilities').contains('Health Station');
  fields['institution_school'] = value('institutional_facilities').contains('School');
  fields['leader_bhw'] = value('recognized_non_formal_leaders').contains('BHW');
  fields['leader_captain'] = value('recognized_formal_elected_leaders').contains('Captain');
  fields['leader_elderly'] = value('recognized_non_formal_leaders').contains('Elderly');
  fields['leader_influential_person'] = value('recognized_non_formal_leaders').contains('Influential person');
  fields['leader_kagawad'] = value('recognized_formal_elected_leaders').contains('Kagawad');
  fields['leader_neighbor'] = value('recognized_non_formal_leaders').contains('Neighbor');
  fields['leader_religious'] = value('recognized_non_formal_leaders').contains('Religious leader');
  fields['lighting_adequate'] = value('lighting_adequacy') == 'Adequate';
  fields['lighting_electricity'] = value('lighting_facility') == 'Electricity';
  fields['lighting_inadequate'] = value('lighting_adequacy') == 'Inadequate';
  fields['lighting_kerosene'] = value('lighting_facility') == 'Kerosene';
  fields['lighting_others_checked'] = value('lighting_facility') == 'Others';
  fields['lighting_others'] = value('lighting_facility_other');
  fields['measure_community_healer'] = value('measures_taken_during_illness').contains('See a known community healer');
  fields['measure_none'] = value('measures_taken_during_illness').contains('None');
  fields['measure_private_health_worker'] = value('measures_taken_during_illness').contains('Consult a private health worker');
  fields['measure_rural_health_team'] = value('measures_taken_during_illness').contains('Consult a Rural Health Team');
  fields['measure_self_medication'] = value('measures_taken_during_illness').contains('Self-Medication');
  fields['medical_checkup_more_than_year'] = value('medical_checkup_frequency') == 'More than a year';
  fields['medical_checkup_once_year'] = value('medical_checkup_frequency') == 'Once a year';
  fields['medical_checkup_twice_year'] = value('medical_checkup_frequency') == 'Twice a year';
  fields['medication_herbals'] = value('medication_treatment_during_illness').contains('Herbals');
  fields['medication_others_checked'] = value('medication_treatment_during_illness').contains('Others');
  fields['medication_others'] = value('medication_treatment_during_illness_other');
  fields['medication_prescribed_doctor'] = value('medication_treatment_during_illness').contains('Prescribed by Doctor');
  fields['medication_self_medication_otc'] = value('medication_treatment_during_illness').contains('Self-Medication/OTC drugs');
  fields['no_segregation_long_time_practice'] = value('reason_for_not_practicing_waste_segregation') == 'Long-time practice of family';
  fields['no_segregation_no_ordinance'] = value('reason_for_not_practicing_waste_segregation') == 'No barangay/municipality ordinance';
  fields['no_segregation_no_time'] = value('reason_for_not_practicing_waste_segregation') == 'No time to do it';
  fields['no_segregation_not_aware'] = value('reason_for_not_practicing_waste_segregation') == 'Not aware of effects';
  fields['org_others'] = value('organizations_other');
  fields['organization_others_checked'] = value('organizations').contains('Others');
  fields['organization_senior_citizen'] = value('organizations').contains('Senior Citizen');
  fields['organization_youth'] = value('organizations').contains('Youth');
  fields['rabies_animals_no'] = value('has_rabies_carrier_animals') == 'No';
  fields['rabies_animals_yes'] = value('has_rabies_carrier_animals') == 'Yes';
  fields['reason_choice_affordable'] = value('reason_for_food_choices').contains('Affordable');
  fields['reason_choice_health_condition'] = value('reason_for_food_choices').contains('Health condition');
  fields['reason_choice_healthy'] = value('reason_for_food_choices').contains('It is healthy');
  fields['reason_choice_personal_belief'] = value('reason_for_food_choices').contains('Personal belief/practices');
  fields['reason_choice_preference'] = value('reason_for_food_choices').contains('Own preference');
  fields['reason_not_choose_health_condition'] = value('reason_for_not_choosing_other_food_options').contains('Health condition');
  fields['reason_not_choose_not_affordable'] = value('reason_for_not_choosing_other_food_options').contains('Not affordable');
  fields['reason_not_choose_not_healthy'] = value('reason_for_not_choosing_other_food_options').contains('Not healthy');
  fields['reason_not_choose_personal_belief'] = value('reason_for_not_choosing_other_food_options').contains('Personal belief/religious practices');
  fields['reason_not_choose_preference'] = value('reason_for_not_choosing_other_food_options').contains('Own preference');
  fields['recreation_basketball_volleyball_court'] = value('recreational_facilities').contains('Volleyball/Basketball court');
  fields['recreation_others_checked'] = value('recreational_facilities').contains('Others');
  fields['recreation_playground'] = value('recreational_facilities').contains('Playground');
  fields['recreation_plaza'] = value('recreational_facilities').contains('Plaza');
  fields['recreational_others'] = value('recreational_facilities_other');
  fields['safety_devices_not_practiced'] = value('uses_safety_devices_when_necessary') == 'Not Practiced';
  fields['safety_devices_practiced'] = value('uses_safety_devices_when_necessary') == 'Practice';
  fields['sanitary_dirty'] = value('general_sanitary_condition') == 'Dirty';
  fields['sanitary_generally_clean'] = value('general_sanitary_condition') == 'Generally clean';
  fields['segregation_reason_barangay_ordinance'] = value('reason_for_practicing_waste_segregation') == 'Barangay ordinance which is strictly monitored';
  fields['segregation_reason_business'] = value('reason_for_practicing_waste_segregation') == 'Use for business';
  fields['segregation_reason_environment_friendly'] = value('reason_for_practicing_waste_segregation') == 'Environmentally friendly';
  fields['segregation_reason_others_checked'] = value('reason_for_practicing_waste_segregation') == 'Others';
  fields['segregation_reason_others'] = value('reason_for_practicing_waste_segregation_other');
  fields['sleeping_rooms_1'] = value('sleeping_rooms_count') == '1';
  fields['sleeping_rooms_2'] = value('sleeping_rooms_count') == '2';
  fields['sleeping_rooms_3'] = value('sleeping_rooms_count') == '3';
  fields['sleeping_rooms_4'] = value('sleeping_rooms_count') == '4';
  fields['sleeping_rooms_5'] = value('sleeping_rooms_count') == '5';
  fields['sleeping_rooms_none'] = value('sleeping_rooms_count') == 'None/no partition';
  fields['space_adequate'] = value('home_space_adequacy') == 'Adequate';
  fields['space_inadequate'] = value('home_space_adequacy') == 'Inadequate';
  fields['storage_basket'] = value('food_storage_type') == 'Basket';
  fields['storage_cabinet'] = value('food_storage_type') == 'Cabinet';
  fields['storage_refrigerator'] = value('food_storage_type') == 'Refrigerator';
  fields['storage_table'] = value('food_storage_type') == 'Table';
  fields['supplies_available_100'] = value('supplies_equipment_availability') == 'Available 100%';
  fields['supplies_limited'] = value('supplies_equipment_availability') == 'Limited Supplies';
  fields['supplies_not_available'] = value('supplies_equipment_availability') == 'Not Available';
  fields['toilet_ballot_system'] = value('toilet_type') == 'Ballot system';
  fields['toilet_flush_type'] = value('toilet_type') == 'Flush type';
  fields['toilet_location_20ft_beyond'] = value('toilet_location_from_water_source') == '20 ft. beyond';
  fields['toilet_location_less_20ft'] = value('toilet_location_from_water_source') == 'Less than 20 ft.';
  fields['toilet_none'] = value('toilet_ownership') == 'None';
  fields['toilet_other_checked'] = value('toilet_type') == 'Other';
  fields['toilet_overhung_latrine'] = value('toilet_type') == 'Overhung latrine';
  fields['toilet_owned'] = value('toilet_ownership') == 'Owned';
  fields['toilet_pail_system'] = value('toilet_type') == 'Pail system';
  fields['toilet_sanitary_clean'] = value('toilet_sanitary_condition') == 'Generally clean';
  fields['toilet_sanitary_dirty'] = value('toilet_sanitary_condition') == 'Dirty';
  fields['toilet_shared_public'] = value('toilet_ownership') == 'Shared/Public';
  fields['toilet_type_none'] = value('toilet_type') == 'None';
  fields['toilet_type_other'] = value('toilet_type_other');
  fields['toilet_water_sealed'] = value('toilet_type') == 'Water-sealed';
  fields['tradition_bayanihan'] = value('traditions_customs').contains('Bayanihan');
  fields['tradition_close_family_ties'] = value('traditions_customs').contains('Close family ties');
  fields['tradition_custom_other'] = value('traditions_customs_other');
  fields['tradition_fiestas'] = value('traditions_customs').contains('Fiestas');
  fields['tradition_ningas_kugon'] = value('traditions_customs').contains('Ningas Kugon');
  fields['tradition_others_checked'] = value('traditions_customs').contains('Others');
  fields['tradition_pakikisama'] = value('traditions_customs').contains('Pakikisama');
  fields['tradition_palabra_de_honor'] = value('traditions_customs').contains('Palabra de Honor');
  fields['tradition_respect_for_elderly'] = value('traditions_customs').contains('Respect for elderly');
  fields['transport_bicycle'] = value('mode_of_transportation').contains('Bicycle');
  fields['transport_jeep'] = value('mode_of_transportation').contains('Jeep');
  fields['transport_private_vehicle'] = value('mode_of_transportation').contains('Private vehicle');
  fields['transport_puj_puv'] = value('mode_of_transportation').contains('PUJ/PUV');
  fields['transport_tricycle'] = value('mode_of_transportation').contains('Tricycle');
  fields['vector_control_cleaning_yard'] = value('vector_control_measures').contains('Cleaning the yard');
  fields['vector_control_fumigation'] = value('vector_control_measures').contains('Fumigation');
  fields['vector_control_insecticides'] = value('vector_control_measures').contains('Insecticides');
  fields['vector_control_none'] = value('vector_control_measures').contains('None');
  fields['vector_control_traps'] = value('vector_control_measures').contains('Setting traps');
  fields['ventilation_adequate'] = value('ventilation_adequacy') == 'Adequate';
  fields['ventilation_inadequate'] = value('ventilation_adequacy') == 'Inadequate';
  fields['waste_segregation_not_practiced'] = value('waste_segregation') == 'Not Practiced';
  fields['waste_segregation_practiced'] = value('waste_segregation') == 'Practiced';
  fields['water_bathing_commercial'] = value('water_source_bathing_cr_flushing') == 'Commercial';
  fields['water_bathing_deep_well'] = value('water_source_bathing_cr_flushing') == 'Deep well';
  fields['water_bathing_local_district'] = value('water_source_bathing_cr_flushing') == 'Local Water District';
  fields['water_bathing_others_checked'] = value('water_source_bathing_cr_flushing') == 'Others';
  fields['water_bathing_others'] = value('water_source_bathing_cr_flushing_other');
  fields['water_cooking_commercial'] = value('water_source_cooking') == 'Commercial';
  fields['water_cooking_deep_well'] = value('water_source_cooking') == 'Deep well';
  fields['water_cooking_local_district'] = value('water_source_cooking') == 'Local Water District';
  fields['water_cooking_others_checked'] = value('water_source_cooking') == 'Others';
  fields['water_cooking_others'] = value('water_source_cooking_other');
  fields['water_drinking_commercial'] = value('water_source_drinking') == 'Commercial';
  fields['water_drinking_deep_well'] = value('water_source_drinking') == 'Deep well';
  fields['water_drinking_local_district'] = value('water_source_drinking') == 'Local Water District';
  fields['water_drinking_others_checked'] = value('water_source_drinking') == 'Others';
  fields['water_drinking_others'] = value('water_source_drinking_other');
  fields['water_ownership_private'] = value('water_supply_ownership') == 'Private';
  fields['water_ownership_public'] = value('water_supply_ownership') == 'Public';
  fields['water_potable_no'] = value('water_potability_key_informant') == 'No';
  fields['water_potable_yes'] = value('water_potability_key_informant') == 'Yes';
  fields['water_source_distance'] = value('water_source_distance_from_house');
  fields['water_storage_large_covered_with_faucet'] = value('water_storage') == 'Large covered container with faucet';
  fields['water_storage_large_covered_without_faucet'] = value('water_storage') == 'Large covered container without faucet';
  fields['water_storage_large_uncovered_with_faucet'] = value('water_storage') == 'Large uncovered container with faucet';
  fields['water_storage_large_uncovered_without_faucet'] = value('water_storage') == 'Large uncovered container without faucet';
  fields['water_storage_none_direct'] = value('water_storage') == 'None/direct from faucet or pipe';
  fields['water_storage_others_checked'] = value('water_storage') == 'Others';
  fields['water_storage_others'] = value('water_storage_other');
