  fields['bhc_services_aware'] = value('awareness_of_health_services') == 'Aware';
  fields['bhc_services_unaware'] = value('awareness_of_health_services') == 'Unaware';
  fields['bought_food_everyday'] = value('food_preparation_frequency') == 'Everyday';
  fields['bought_food_once_week'] = value('food_preparation_frequency') == 'Once a week';
  fields['bought_food_others_checked'] = value('food_preparation_frequency') == 'Others';
  fields['bought_food_twice_week'] = value('food_preparation_frequency') == 'Twice a week';
  fields['bought_from_carinderia'] = value('bought_food_source').contains('Carinderia');
  fields['bought_from_food_cart'] = value('bought_food_source').contains('Food cart');
  fields['bought_from_restaurant_fastfood'] = value('bought_food_source').contains('Restaurant/Fast food');
  fields['communication_cellphone'] = value('mode_of_communication').contains('Cell phone');
  fields['communication_postal'] = value('mode_of_communication').contains('Postal system');
  fields['community_involvement_active'] = value('community_involvement') == 'Actively joins fiesta, religious procession, local cultural practices';
  fields['community_involvement_not_active'] = value('community_involvement') == 'Does not actively join';
  fields['community_services_garbage_collection'] = value('services_in_community').contains('Garbage collection');
  fields['community_services_livelihood_duplicate'] = value('services_in_community').contains('Livelihood Services');
  fields['community_services_peace_order'] = value('services_in_community').contains('Peace and Order');
  fields['construction_light'] = value('home_construction_materials') == 'Light';
  fields['construction_mixed'] = value('home_construction_materials') == 'Mixed';
  fields['construction_strong_concrete'] = value('home_construction_materials') == 'Strong/Concrete';
  fields['consult_albularyo'] = value('personnel_consulted_during_illness').contains('Albularyo');
  fields['consult_doctor'] = value('personnel_consulted_during_illness').contains('Doctor');
  fields['consult_elderly'] = value('personnel_consulted_during_illness').contains('Elderly');
  fields['consult_faith_healer'] = value('personnel_consulted_during_illness').contains('Faith Healer');
  fields['consult_hilot'] = value('personnel_consulted_during_illness').contains('Hilot');
  fields['consult_midwife'] = value('personnel_consulted_during_illness').contains('Midwife');
  fields['consult_nurse'] = value('personnel_consulted_during_illness').contains('Nurse');
  fields['cooking_sanitary_dirty'] = value('cooking_area_sanitary_condition') == 'Dirty';
  fields['cooking_sanitary_generally_clean'] = value('cooking_area_sanitary_condition') == 'Generally clean';
  fields['cultural_practices_always'] = value('cultural_perception_health_practices') == 'Always practices local cultural practices about health matters';
  fields['cultural_practices_does_not_practice'] = value('cultural_perception_health_practices') == 'Does not practice any local cultural practices about health matters';
  fields['cultural_practices_sometimes'] = value('cultural_perception_health_practices') == 'Sometimes practices local cultural practices about health matters';
  fields['disposal_not_practiced_burial_pit'] = value('waste_disposal_method_if_not_practiced') == 'Burial in pit';
  fields['disposal_not_practiced_collected'] = value('waste_disposal_method_if_not_practiced') == 'Collected';
  fields['disposal_not_practiced_composting'] = value('waste_disposal_method_if_not_practiced') == 'Composting';
  fields['disposal_not_practiced_hog_feeding'] = value('waste_disposal_method_if_not_practiced') == 'Hog-feeding';
  fields['disposal_not_practiced_open_burning'] = value('waste_disposal_method_if_not_practiced') == 'Open burning';
  fields['disposal_not_practiced_open_dumping'] = value('waste_disposal_method_if_not_practiced') == 'Open dumping';
  fields['disposal_practiced_burial_pit'] = value('waste_disposal_method_if_practiced') == 'Burial in pit';
  fields['disposal_practiced_collected'] = value('waste_disposal_method_if_practiced') == 'Collected';
  fields['disposal_practiced_composting'] = value('waste_disposal_method_if_practiced') == 'Composting';
  fields['disposal_practiced_hog_feeding'] = value('waste_disposal_method_if_practiced') == 'Hog-feeding';
  fields['disposal_practiced_open_burning'] = value('waste_disposal_method_if_practiced') == 'Open burning';
  fields['disposal_practiced_open_dumping'] = value('waste_disposal_method_if_practiced') == 'Open dumping';
  fields['drainage_flowing'] = value('drainage_condition') == 'Flowing';
  fields['drainage_stagnant'] = value('drainage_condition') == 'Stagnant';
  fields['drug_types_checked'] = value('family_member_uses_drugs') == 'Yes';
  fields['drug_use_no'] = value('family_member_uses_drugs') == 'No';
  fields['drug_use_yes'] = value('family_member_uses_drugs') == 'Yes';
  fields['family_composition_blended'] = value('type_of_family_composition') == 'Blended Family';
  fields['family_composition_cohabiting_communal'] = value('type_of_family_composition') == 'Cohabiting/Communal';
  fields['family_composition_dyad'] = value('type_of_family_composition') == 'Dyad';
  fields['family_composition_extended'] = value('type_of_family_composition') == 'Extended';
  fields['family_composition_living_with_grandparents'] = value('type_of_family_composition') == 'Living with Grandparent(s)';
  fields['family_composition_nuclear'] = value('type_of_family_composition') == 'Nuclear';
  fields['family_composition_same_sex'] = value('type_of_family_composition') == 'Homosexual/Same Sex';
  fields['family_composition_single_parent'] = value('type_of_family_composition') == 'Single- parent';
  fields['family_descent_bilateral'] = value('type_of_family_descent') == 'Bilateral';
  fields['family_descent_matrilineal'] = value('type_of_family_descent') == 'Matrilineal';
  fields['family_descent_patrilineal'] = value('type_of_family_descent') == 'Patrilineal';
  fields['family_power_egalitarian'] = value('type_of_family_locus_of_power') == 'Egalitarian';
  fields['family_power_matricentric'] = value('type_of_family_locus_of_power') == 'Matricentric';
  fields['family_power_matrifocal_matriarchal'] = value('type_of_family_locus_of_power') == 'Matrifocal/Matriarchal';
  fields['family_power_patrifocal_patriarchal'] = value('type_of_family_locus_of_power') == 'Patrifocal/Patriarchal';
  fields['family_residence_bilocal_ambilocal'] = value('type_of_family_place_of_residence') == 'Bilocal (Ambilocal)';
  fields['family_residence_matrilocal'] = value('type_of_family_place_of_residence') == 'Matrilocal';
  fields['family_residence_neolocal'] = value('type_of_family_place_of_residence') == 'Neolocal';
  fields['family_residence_patrilocal'] = value('type_of_family_place_of_residence') == 'Patrilocal';
  fields['financial_source_help_relative_friends'] = value('financial_sources').contains('Help from relative/friends');
  fields['food_first_fish'] = value('first_food_choice') == 'Fish';
  fields['food_first_meat_only'] = value('first_food_choice') == 'Meat only';
  fields['food_first_mixed'] = value('first_food_choice') == 'Mixed';
  fields['food_first_others_checked'] = value('first_food_choice') == 'Others';
  fields['food_first_serving_1'] = value('first_food_choice_servings') == '1';
  fields['food_first_serving_2_3'] = value('first_food_choice_servings') == '2-3';
  fields['food_first_serving_4_5_above'] = value('first_food_choice_servings') == '4-5 and above';
  fields['food_first_vegetable'] = value('first_food_choice') == 'Vegetable';
  fields['food_intake_everyday'] = value('food_intake_frequency') == 'Everyday';
  fields['food_intake_once_week'] = value('food_intake_frequency') == 'Once a week';
  fields['food_intake_others_checked'] = value('food_intake_frequency') == 'Others';
  fields['food_intake_twice_week'] = value('food_intake_frequency') == 'Twice a week';
  fields['food_second_fish'] = value('second_food_choice') == 'Fish';
  fields['food_second_meat'] = value('second_food_choice') == 'Meat';
  fields['food_second_mixed'] = value('second_food_choice') == 'Mixed';
  fields['food_second_others_checked'] = value('second_food_choice') == 'Others';
  fields['food_second_serving_1'] = value('second_food_choice_servings') == '1';
  fields['food_second_serving_2_3'] = value('second_food_choice_servings') == '2-3';
  fields['food_second_serving_4_5_above'] = value('second_food_choice_servings') == '4-5 and above';
  fields['food_second_vegetable'] = value('second_food_choice') == 'Vegetable';
  fields['fp_acceptor_good_for_health'] = value('reason_for_using_family_planning_method').contains('Good for health');
  fields['fp_acceptor_others_checked'] = value('reason_for_using_family_planning_method').contains('Others');
  fields['fp_basal_body_temperature'] = value('family_planning_fertility_awareness_method') == 'Basal Body Temperature (BBT)';
  fields['fp_cervical_mucus'] = value('family_planning_fertility_awareness_method') == 'Cervical Mucus Method / Billings Ovu. Method';
  fields['fp_condoms'] = value('family_planning_supply_method') == 'Condoms';
  fields['fp_female_sterilization'] = value('family_planning_permanent_method') == 'Female sterilization / Bilateral Tubal Ligation';
  fields['fp_fertility_awareness_method'] = value('family_planning_temporary_method') == 'Fertility Awareness-Based Method';
  fields['fp_implant'] = value('family_planning_supply_method') == 'Implant';
  fields['fp_injectable'] = value('family_planning_supply_method') == 'Injectable';
  fields['fp_iud'] = value('family_planning_supply_method') == 'IUD';
  fields['fp_lactational_amenorrhea'] = value('family_planning_fertility_awareness_method') == 'Lactational Amenorrhea Method (LAM)';
  fields['fp_male_sterilization'] = value('family_planning_permanent_method') == 'Male sterilization / Vasectomy';
  fields['fp_nonacceptor_bad_for_health'] = value('reason_for_not_using_family_planning_method').contains('Bad for health');
  fields['fp_nonacceptor_influenced_by_others'] = value('reason_for_not_using_family_planning_method').contains('Influenced by others');
  fields['fp_nonacceptor_others_checked'] = value('reason_for_not_using_family_planning_method').contains('Others');
  fields['fp_nonacceptor_personal_belief'] = value('reason_for_not_using_family_planning_method').contains('Personal belief');
  fields['fp_nonacceptor_religious_belief'] = value('reason_for_not_using_family_planning_method').contains('Religious belief');
  fields['fp_permanent_method'] = value('modern_family_planning_method_used') == 'Permanent method';
  fields['fp_pills'] = value('family_planning_supply_method') == 'Pills';
  fields['fp_standard_days'] = value('family_planning_fertility_awareness_method') == 'Standard Days Method (SDM)';
  fields['fp_supply_methods'] = value('family_planning_temporary_method') == 'Supply Methods';
  fields['fp_sympto_thermal'] = value('family_planning_fertility_awareness_method') == 'Sympto-Thermal Method';
  fields['fp_temporary_method'] = value('modern_family_planning_method_used') == 'Temporary method';
  fields['priority_clothing'] = value('priorities_and_expenditure_ranking').contains('Clothing');
  fields['priority_education'] = value('priorities_and_expenditure_ranking').contains('Education');
  fields['priority_food'] = value('priorities_and_expenditure_ranking').contains('1. Food') || value('priorities_and_expenditure_ranking').contains('Food');
  fields['priority_health'] = value('priorities_and_expenditure_ranking').contains('Health');
  fields['priority_recreation'] = value('priorities_and_expenditure_ranking').contains('Recreation');
  fields['priority_savings'] = value('priorities_and_expenditure_ranking').contains('Savings');
  fields['priority_utilities'] = value('priorities_and_expenditure_ranking').contains('Utilities');
  fields['settlement_barangay_hearing'] = value('effective_practices_setting_issues').contains('Brgy. hearing');
  fields['settlement_local_police'] = value('effective_practices_setting_issues').contains('Endorsed to local police');
  fields['settlement_others_checked'] = value('effective_practices_setting_issues').contains('Others');
  fields['settlement_parties'] = value('effective_practices_setting_issues').contains('Settlement among involved parties');
  fields['smoker_frequency_checked'] = value('family_member_is_cigarette_smoker') == 'Yes';
  fields['smoker_no'] = value('family_member_is_cigarette_smoker') == 'No';
  fields['smoker_yes'] = value('family_member_is_cigarette_smoker') == 'Yes';
  fields['social_conflict_alcohol'] = value('source_of_social_conflict').contains('Alcohol');
  fields['social_conflict_drugs'] = value('source_of_social_conflict').contains('Drugs');
  fields['social_conflict_family'] = value('source_of_social_conflict').contains('Family dispute');
  fields['social_conflict_gossip'] = value('source_of_social_conflict').contains('Gossip');
  fields['social_conflict_others_checked'] = value('source_of_social_conflict').contains('Others');
  fields['social_conflict_riot'] = value('source_of_social_conflict').contains('Riot');
